version: '3.3'
services:
  amq:
    image: vromero/activemq-artemis:latest
    container_name: activemq
    environment:
      ARTEMIS_USERNAME: user-amq
      ARTEMIS_PASSWORD: password-amq
    ports:
      - 8161:8161
      - 61616:61616